### PR TITLE
Feature: Add a Helm Chart for Vigilo

### PR DESCRIPTION
**Pull request by ardelato**
## Description

This mainly follows examples I've seen from other Helm Charts. The entire premise to be able to routinely kick off a lighthouse audit as part of our Kubernetes cluster. This will detach the dependency of having Lighthouse running on our Ubreakit machine and instead will be ran through a Pod. 

As such, it will be a lot easier if we have a Helm Chart for all this instead of manually creating the manifests ourselves in our FluxCD repo.

### QA 

> [!Note]
> This will be difficult to QA as is, we will need to manually test by integrating the Helm Chart into our current Test cluster.

1. Declare a new `GitRepository` FluxCD resource
2. Define a Helm Release
	- Use the AWS ECR repo in the values section
4. Check if the CronJob worked successfully.

Closes: https://github.com/iFixit/vigilo/issues/16
Connects: https://github.com/iFixit/ifixit/issues/49455

### CODE REVIEW

**Review by mlahargou — COMMENTED** [review]
Are there any helm linters that we can enable in this repo?

maybe https://github.com/marketplace/actions/helm-chart-testing?

**Review by mlahargou — APPROVED** [review]
CR ❓ It's a bit hard to CR this as I'm not very familiar with helm chart generation. Kinda one of those things we just need to QA I think.

**Comment by ardelato** [comment]
> Are there any helm linters that we can enable in this repo?
> 
> maybe [github.com/marketplace/actions/helm-chart-testing](https://github.com/marketplace/actions/helm-chart-testing)?

There are a couple things I want to add to help automate some of the Helm stuff. For instance, the usage of `helm-docs` to automatically create a corresponding `README.md` https://github.com/norwoodj/helm-docs

That said, I think we should create follow-up issues to address the testing aspect.

**Comment by ardelato** [comment]
> CR ❓ It's a bit hard to CR this as I'm not very familiar with helm chart generation. Kinda one of those things we just need to QA I think.

This is still in the early phases for us, so manual testing will be the initial validation to the charts. That said, one thing I should point out is that unlike some of the other Helm Charts we've interacted with, this uses a [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) instead of a `Deployment` to kick off a `Pod`.

**Comment by ardelato** [comment]
QA 👍 

I was able to get Vigilo integrated and working in the test cluster without any modifications to the current Helm Chart.

image

image

**Pull request merged**
